import { assets } from "@/lib/assets";

export const workData = [
  {
    title: "Docmify - PDF Tools",
    description: "Online PDF Management Suite",
    fullDescription: "Docmify offers a comprehensive set of free online PDF tools. Users can easily merge, split, compress, and convert PDF files with a focus on security and simplicity. The intuitive interface ensures efficient document management directly in the browser.",
    bgImage: assets.work3,
    preview: assets.work3,
    live: "https://docmify.vercel.app/",
    github: null,
  },
  {
    title: "Traffic Safety Analysis",
    description: "AI-Powered Traffic Safety",
    fullDescription: "Developed an automated traffic safety analysis system for heterogeneous traffic environments using computer vision and deep learning. Implemented algorithms to extract vehicle trajectories and calculate critical safety surrogate measures including Time to Collision (TTC), Post Encroachment Time (PET), Deceleration to Safety Time (DST), and Gap Time (GT). Utilized YOLO for object detection and SORT/DeepSORT for multi-object tracking to analyze complex traffic interactions and predict potential conflicts.",
    bgImage: assets.work1,
    preview: assets.work1,
    live: null,
    github: "https://drive.google.com/drive/folders/1mjBtJ93uugmWMlRtuKcogYqrTmUIGdZ5",
    download: "https://avinashg0y4l.github.io/portfolio/assets/IIT_Jodhpur_report.docx",
  },
  {
    title: "AI Recruitment",
    description: "Screening and Shortlisting",
    fullDescription:
      "Created an AI-powered recruitment assistant that uses multi-agent architecture to analyze job descriptions, filter resumes, and shortlist candidates automatically. Includes NLP models and a scoring engine for unbiased hiring.",
    bgImage: assets.work2,
    preview: assets.work2,
    live: "",
    github: null,
  },
  {
    title: "Design Portfolio",
    description: "Personal portfolio website for a professional graphic designer.",
    fullDescription:
      "Developed a responsive and modern portfolio website for a professional graphic designer. The site highlights their creative projects with a clean gallery layout, smooth animations, and strong emphasis on typography. The design ensures both aesthetic appeal and performance, providing an engaging user experience while showcasing the designer’s work to potential clients.",
    bgImage: assets.designPortfolio,
    preview: assets.designPortfolio,
    live: "https://rahul-s-portfolio-tau.vercel.app/",
    github: null,
  },
  {
    title: "BottleCar_Robor",
    description: "ROS Simulation",
    fullDescription: "ROS-based simulation of an autonomous bottle car robot using Gazebo and RViz. Implemented SLAM, path planning, and obstacle avoidance algorithms to enable autonomous navigation in a dynamic environment.",
    bgImage: assets.bottlecar_robor,
    preview: assets.bottlecar_robor,
    live: null,
    github: "https://github.com/avinashg0y4l/ros-bottle-car-simulation",
  },
  {
    title: "USD to another Currency Converter",
    description: "Currency Converter",
    fullDescription: "Developed a currency converter tool that allows users to convert USD to various other currencies in real-time. The tool fetches live exchange rates and provides a user-friendly interface for seamless conversions.",
    bgImage: assets.usd_to_currency_converter,
    preview: assets.usd_to_currency_converter,
    live: "https://usd-2-another-currency-convertor.vercel.app/",
    github: "https://github.com/avinashg0y4l/usd_2_another_currency_convertor",
  },
  {
    title: "UI/UX Designing",
    description: "UI/UX Design",
    fullDescription:
      "Crafted multiple UI/UX design prototypes for mobile and web applications, focusing on accessibility, clean design systems, and user flow optimization.",
    bgImage: assets.work4,
    preview: assets.work4,
    live: null,
    github: null,
  },
  {
    title: "JNV Pauri Garhwal workshop",
    description: "Workshop Portfolio",
    fullDescription: "A portfolio workshop project for JNV Pauri Garhwal.",
    bgImage: assets.jnv_workshop,
    preview: assets.jnv_workshop,
    live: null,
    github: "https://github.com/avinashg0y4l/workshop_portfolio_JNV_pauri",
    download: "https://github.com/avinashg0y4l/workshop_portfolio_JNV_pauri/archive/refs/heads/main.zip",
  },
];
